#!/bin/bash

SOURCE_DIR=whoiscache

set -e

bin/venv_init

. venv/bin/activate

pip install -r requirements-test.txt

nosetests -v --with-xunit --cover-erase --cover-inclusive --cover-html --cover-package=$SOURCE_DIR tests

